export const MOCK_ROWS = [
  {
    id: "row-1",
    counterpartType: "proveedores",
    segment: "proveedores-generales-pj-y-financieras",
    nombre: "ACME S.A.S.",
    email: "contacto@acme.com",
    tipoDocumento: "NIT",
    numeroDocumento: "901234567-8",
    firmadoUrl: "#",
    docs: {
      RUT: {
        status: "pendiente",
        comentario: "",
        fileName: "",
        updatedAt: null,
      },
      "Cámara de Comercio": {
        status: "pendiente",
        comentario: "",
        fileName: "",
        updatedAt: null,
      },
      "CC Representante": {
        status: "pendiente",
        comentario: "",
        fileName: "",
        updatedAt: null,
      },
      "Certificación Bancaria": {
        status: "aprobado",
        comentario: "Vigente",
        fileName: "cert_banco.pdf",
        updatedAt: "2025-11-10T10:30:00.000Z",
      },
      "Formato Conocimiento": {
        status: "rechazado",
        comentario: "Falta firma",
        fileName: "",
        updatedAt: "2025-11-10T11:15:00.000Z",
      },
    },
  },
  {
    id: "row-2",
    counterpartType: "clientes",
    segment: "aliados-retomadores-pn",
    nombre: "Juan Pérez",
    email: "juan.perez@example.com",
    tipoDocumento: "CC",
    numeroDocumento: "1090xxxxxx",
    firmadoUrl: "#",
    docs: {
      CC: {
        status: "aprobado",
        comentario: "",
        fileName: "cc_juan.pdf",
        updatedAt: "2025-11-11T08:00:00.000Z",
      },
      "Certificación Laboral/Ingresos": {
        status: "pendiente",
        comentario: "",
        fileName: "",
        updatedAt: null,
      },
      "Formato Conocimiento": {
        status: "pendiente",
        comentario: "",
        fileName: "",
        updatedAt: null,
      },
    },
  },
  {
    id: "row-3",
    counterpartType: "accionistas",
    segment: "personas-juridicas",
    nombre: "Inversiones XYZ S.A.",
    email: "info@xyz.com",
    tipoDocumento: "NIT",
    numeroDocumento: "900123456-1",
    firmadoUrl: "#",
    docs: {
      "Cámara de Comercio": {
        status: "pendiente",
        comentario: "",
        fileName: "",
        updatedAt: null,
      },
      "Representación Legal": {
        status: "pendiente",
        comentario: "",
        fileName: "",
        updatedAt: null,
      },
      "CC Representante": {
        status: "rechazado",
        comentario: "Copia ilegible",
        fileName: "",
        updatedAt: "2025-11-09T16:45:00.000Z",
      },
    },
  },
];
